"""add_v2_vuln_columns

Revision ID: 86b13a6cc72e
Revises: fba8b695865f
Create Date: 2026-06-30 17:49:20.276028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b13a6cc72e'
down_revision: Union[str, None] = 'fba8b695865f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerability_findings', sa.Column('true_risk_score', sa.Float(), nullable=True))
    op.add_column('vulnerability_findings', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('vulnerability_findings', sa.Column('asset_criticality', sa.String(length=5), nullable=True))
    op.add_column('vulnerability_findings', sa.Column('asset_owner', sa.String(length=100), nullable=True))
    op.add_column('vulnerability_findings', sa.Column('internet_facing', sa.String(length=5), nullable=True))
    op.add_column('vulnerability_findings', sa.Column('first_detected', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerability_findings', 'first_detected')
    op.drop_column('vulnerability_findings', 'internet_facing')
    op.drop_column('vulnerability_findings', 'asset_owner')
    op.drop_column('vulnerability_findings', 'asset_criticality')
    op.drop_column('vulnerability_findings', 'location')
    op.drop_column('vulnerability_findings', 'true_risk_score')
    # ### end Alembic commands ###
