"""init

Revision ID: fba8b695865f
Revises: 
Create Date: 2026-06-27 11:54:42.468594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba8b695865f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('is_folder', sa.Boolean(), nullable=False),
    sa.Column('main_playbook_file', sa.String(length=255), nullable=True),
    sa.Column('file_structure', sa.JSON(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_size_kb', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbooks_name'), 'playbooks', ['name'], unique=True)
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('os_type', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('ssh_user', sa.String(length=50), nullable=False),
    sa.Column('ssh_key_path', sa.String(length=500), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('disk_usage', sa.Float(), nullable=True),
    sa.Column('last_monitored', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servers_ip_address'), 'servers', ['ip_address'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin', 'user', name='user_roles'), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('parent_job_id', sa.Integer(), nullable=True),
    sa.Column('is_batch_job', sa.Boolean(), nullable=False),
    sa.Column('batch_config', sa.JSON(), nullable=True),
    sa.Column('playbook_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', 'cancelled', name='job_status'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('extra_vars', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('patch_report', sa.Text(), nullable=True),
    sa.Column('report_files', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('csv_minio_path', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_status_created', 'jobs', ['status', 'created_at'], unique=False)
    op.create_index('idx_job_user_status', 'jobs', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_celery_task_id'), 'jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_jobs_is_batch_job'), 'jobs', ['is_batch_job'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_jobs_parent_job_id'), 'jobs', ['parent_job_id'], unique=False)
    op.create_index(op.f('ix_jobs_playbook_id'), 'jobs', ['playbook_id'], unique=False)
    op.create_index(op.f('ix_jobs_server_id'), 'jobs', ['server_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_type', name='uq_user_event_pref')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('playbook_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playbook_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['playbook_id'], ['playbooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbook_audit_logs_playbook_id'), 'playbook_audit_logs', ['playbook_id'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('server_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('minio_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_runs_run_id'), 'scan_runs', ['run_id'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('job_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_logs_job_line', 'job_logs', ['job_id', 'line_number'], unique=False)
    op.create_index(op.f('ix_job_logs_job_id'), 'job_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_logs_timestamp'), 'job_logs', ['timestamp'], unique=False)
    op.create_table('server_tags',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', 'tag_id')
    )
    op.create_table('vulnerability_findings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('scan_run_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('network', sa.String(length=255), nullable=True),
    sa.Column('dns', sa.String(length=255), nullable=True),
    sa.Column('netbios', sa.String(length=255), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('cve_id', sa.String(length=50), nullable=True),
    sa.Column('vendor_reference', sa.String(length=100), nullable=True),
    sa.Column('threat', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('qds', sa.Float(), nullable=True),
    sa.Column('asset_group', sa.String(length=100), nullable=True),
    sa.Column('server_role', sa.String(length=100), nullable=True),
    sa.Column('last_scan_date', sa.Date(), nullable=True),
    sa.Column('scan_status', sa.String(length=20), nullable=True),
    sa.Column('os_family', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vuln_cve_id', 'vulnerability_findings', ['cve_id'], unique=False)
    op.create_index('idx_vuln_ip', 'vulnerability_findings', ['ip'], unique=False)
    op.create_index('idx_vuln_scan_run', 'vulnerability_findings', ['scan_run_id'], unique=False)
    op.create_index('idx_vuln_severity', 'vulnerability_findings', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vuln_severity', table_name='vulnerability_findings')
    op.drop_index('idx_vuln_scan_run', table_name='vulnerability_findings')
    op.drop_index('idx_vuln_ip', table_name='vulnerability_findings')
    op.drop_index('idx_vuln_cve_id', table_name='vulnerability_findings')
    op.drop_table('vulnerability_findings')
    op.drop_table('server_tags')
    op.drop_index(op.f('ix_job_logs_timestamp'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_job_id'), table_name='job_logs')
    op.drop_index('idx_job_logs_job_line', table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_scan_runs_run_id'), table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_playbook_audit_logs_playbook_id'), table_name='playbook_audit_logs')
    op.drop_table('playbook_audit_logs')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_server_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_playbook_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_parent_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_batch_job'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_celery_task_id'), table_name='jobs')
    op.drop_index('idx_job_user_status', table_name='jobs')
    op.drop_index('idx_job_status_created', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_servers_ip_address'), table_name='servers')
    op.drop_table('servers')
    op.drop_index(op.f('ix_playbooks_name'), table_name='playbooks')
    op.drop_table('playbooks')
    # ### end Alembic commands ###
